name = "QED"
uuid = "bb1fba1d-cf9b-41b3-874e-4b81465537b9"
authors = [
    "Uwe Hernandez Acosta <u.hernandez@hzdr.de>",
    "Simeon Ehrig",
    "Klaus Steiniger",
    "Tom Jungnickel",
    "Anton Reinhard",
]
version = "0.1.0"

[deps]
QEDbase = "10e22c08-3ccb-4172-bfcf-7d7aa3d04d93"
QEDevents = "fc3ce04a-5be5-4f3a-acff-eceaab723759"
QEDfields = "ac3a6c97-e859-4b9f-96bb-63d2a216042c"
QEDprocesses = "46de9c38-1bb3-4547-a1ec-da24d767fdad"

[compat]
julia = "1.6"
