name = "integTestGen"
uuid = "9d227159-adef-4c8b-a714-76f31b0c245d"
authors = ["Simeon Ehrig <s.ehrig@hzdr.de>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PkgDependency = "9eb5382b-762c-48ca-8139-e736883fe800"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
